// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALM62rXympv6akAsC-2YIyKvnHn9_v3og',
    appId: '1:1001153353947:web:753ebed9db2b11515614fe',
    messagingSenderId: '1001153353947',
    projectId: 'meowmin-34db1',
    authDomain: 'meowmin-34db1.firebaseapp.com',
    storageBucket: 'meowmin-34db1.firebasestorage.app',
    measurementId: 'G-EJYEJ2XFT7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJcutitXJsnNfQGpkMZD7OWETVNpSCj9A',
    appId: '1:1001153353947:android:b149e20257ef3c9c5614fe',
    messagingSenderId: '1001153353947',
    projectId: 'meowmin-34db1',
    storageBucket: 'meowmin-34db1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8FWiD3l0Q81Z0dSJ4hBhEXXFWN_g0Km0',
    appId: '1:1001153353947:ios:861c31f5200db1395614fe',
    messagingSenderId: '1001153353947',
    projectId: 'meowmin-34db1',
    storageBucket: 'meowmin-34db1.firebasestorage.app',
    iosBundleId: 'com.taucity.meowmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8FWiD3l0Q81Z0dSJ4hBhEXXFWN_g0Km0',
    appId: '1:1001153353947:ios:6c98e8960d5dd5765614fe',
    messagingSenderId: '1001153353947',
    projectId: 'meowmin-34db1',
    storageBucket: 'meowmin-34db1.firebasestorage.app',
    iosBundleId: 'com.example.ramadanApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALM62rXympv6akAsC-2YIyKvnHn9_v3og',
    appId: '1:1001153353947:web:207924e5b74c94265614fe',
    messagingSenderId: '1001153353947',
    projectId: 'meowmin-34db1',
    authDomain: 'meowmin-34db1.firebaseapp.com',
    storageBucket: 'meowmin-34db1.firebasestorage.app',
    measurementId: 'G-HMX736JRG9',
  );

}