// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDS02CESoPw0BCduBG5KYJnjCHshYrhtf0',
    appId: '1:1059339297432:web:d2bd974fcb2c1a253a66ed',
    messagingSenderId: '1059339297432',
    projectId: 'aliapp-909a0',
    authDomain: 'aliapp-909a0.firebaseapp.com',
    storageBucket: 'aliapp-909a0.firebasestorage.app',
    measurementId: 'G-3NPYHF9WC8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjcFTIEKfX3FjaFBXnzi4_PHSJl-gsECI',
    appId: '1:1059339297432:android:608dc44c27bb755c3a66ed',
    messagingSenderId: '1059339297432',
    projectId: 'aliapp-909a0',
    storageBucket: 'aliapp-909a0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4oc5jxlRhc49Cly161hjcNWe_QrTIM4c',
    appId: '1:1059339297432:ios:762ae6339812bdcb3a66ed',
    messagingSenderId: '1059339297432',
    projectId: 'aliapp-909a0',
    storageBucket: 'aliapp-909a0.firebasestorage.app',
    iosClientId: '1059339297432-ebut10jtshmkgg4vf6a3frgioc5p60ob.apps.googleusercontent.com',
    iosBundleId: 'com.example.ramadanApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4oc5jxlRhc49Cly161hjcNWe_QrTIM4c',
    appId: '1:1059339297432:ios:762ae6339812bdcb3a66ed',
    messagingSenderId: '1059339297432',
    projectId: 'aliapp-909a0',
    storageBucket: 'aliapp-909a0.firebasestorage.app',
    iosClientId: '1059339297432-ebut10jtshmkgg4vf6a3frgioc5p60ob.apps.googleusercontent.com',
    iosBundleId: 'com.example.ramadanApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDS02CESoPw0BCduBG5KYJnjCHshYrhtf0',
    appId: '1:1059339297432:web:905214871de532de3a66ed',
    messagingSenderId: '1059339297432',
    projectId: 'aliapp-909a0',
    authDomain: 'aliapp-909a0.firebaseapp.com',
    storageBucket: 'aliapp-909a0.firebasestorage.app',
    measurementId: 'G-J0HPWW3V92',
  );

}